//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_ThemXoaSua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public string TENBAIVIET { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYVIET { get; set; }
        public string NGUOIVIET { get; set; }
        public string NOIDUNG { get; set; }
        public string HINHANH { get; set; }
        public Nullable<bool> HIENTHI { get; set; }
        public Nullable<int> THUTU { get; set; }
        public int IDBAIVIET { get; set; }
    
        public virtual LoaiBaiViet LoaiBaiViet { get; set; }
    }
}
