//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetNoiDenDataBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHANG
    {
        public int ID { get; set; }
        public string TENKH { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string GIOITINH { get; set; }
        public string TENANH { get; set; }
    }
}
