//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetNoiDenDataBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYTINH
    {
        public int ID { get; set; }
        public string TENMT { get; set; }
        public string HANGSX { get; set; }
        public Nullable<int> NAMSANXUAT { get; set; }
    }
}
